### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#115]
From time to time when I misconfigure config.json I get:

```
/home/sasha/go/src/github.com/gravitational/next/__build/utils/data-fetcher-docs.js:69
            throw Error("File " + path + " didn't include 'navigation' field.");
                  ^

Error: File /home/sasha/go/src/github.com/gravitational/next/content/6.0/docs/config.json didn't include 'navigation' field.
    at Object.getConfig (/home/sasha/go/src/github.com/gravitational/next/__build/utils/data-fetcher-docs.js:69:19)
    at Object.parseMdxContent (/home/sasha/go/src/github.com/gravitational/next/__build/utils/data-fetcher-docs.js:80:22)
    at Object.<anonymous> (/home/sasha/go/src/github.com/gravitational/next/__build/loaders/mdx-loader.js:60:46)
    at step (/home/sasha/go/src/github.com/gravitational/next/__build/loaders/mdx-loader.js:33:23)
    at Object.next (/home/sasha/go/src/github.com/gravitational/next/__build/loaders/mdx-loader.js:14:53)
    at /home/sasha/go/src/github.com/gravitational/next/__build/loaders/mdx-loader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sasha/go/src/github.com/gravitational/next/__build/loaders/mdx-loader.js:4:12)
    at Object.module.exports (/home/sasha/go/src/github.com/gravitational/next/__build/loaders/mdx-loader.js:49:12)
    at LOADER_EXECUTION (/home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:31690:14)
    at runSyncOrAsync (/home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:31691:4)
    at iterateNormalLoaders (/home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:31803:2)
    at Array.<anonymous> (/home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:31776:4)
    at Storage.finished (/home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:22941:16)
    at /home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:22977:9
    at /home/sasha/go/src/github.com/gravitational/next/node_modules/next/dist/compiled/webpack/bundle4.js:29578:16
error Command failed with exit code 1.
```

Please improve the error message, right now it's hard to understand what is wrong

**Comment by iAdramelk** [comment]
Fixed by adding json-schema validation.
