### ISSUE TITLE
Trying to run local dev version

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#70]
Following the readme:

```
~/go/src/github.com/gravitational/next: yarn dev
yarn run v1.21.1
warning ../../../../../package.json: No license field
$ next dev
/bin/sh: 1: next: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/go/src/github.com/gravitational/next: 
```

**Comment by klizhentas** [comment]
I think readme is missing `yarn install` step

**Comment by klizhentas** [comment]
Please send a PR to Teleport docs to update our makefile and README as well

**Comment by klizhentas** [comment]
@iAdramelk seems like I ran out of RAM trying to run a local dev version:

```
~/go/src/github.com/gravitational/next: yarn dev
yarn run v1.21.1
warning ../../../../../package.json: No license field
$ yarn git-update && yarn build-loaders && next dev
warning ../../../../../package.json: No license field
$ git submodule update --remote
warning ../../../../../package.json: No license field
$ rm -rf __build && ttsc --build tsconfig.loaders.json
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Loaded env from /home/sasha/go/src/github.com/gravitational/next/.env.development
Loaded env from /home/sasha/go/src/github.com/gravitational/next/.env
ready - started server on http://localhost:3000
info  - automatically enabled Fast Refresh for 2 custom loaders
info  - Using external babel configuration from /home/sasha/go/src/github.com/gravitational/next/.babelrc
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /[[...slug]]
wait  - compiling...


<--- Last few GCs --->

[1330:0x3c7ae70]   520606 ms: Mark-sweep 2034.3 (2053.2) -> 2034.1 (2053.9) MB, 2239.7 / 0.1 ms  (average mu = 0.086, current mu = 0.002) allocation failure scavenge might not succeed
[1330:0x3c7ae70]   522876 ms: Mark-sweep 2034.5 (2053.9) -> 2034.1 (2053.9) MB, 2265.6 / 0.1 ms  (average mu = 0.045, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x140a8f9]
Security context: 0x38f78c3c08d1 <JSObject>
    1: SourceNode_add [0x936503ed979] [/home/sasha/go/src/github.com/gravitational/next/node_modules/source-map/lib/source-node.js:~172] [pc=0x1c6657e903c](this=0x0f79449c2921 <SourceNode map = 0x302592691a9>,0x1bf00c26d909 <SourceNode map = 0x302592691a9>)
    2: /* anonymous */ [0x1e125b9d9949] [/home/sasha/go/src/github.com/gravitational/next/node_modules/sour...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa18150 node::Abort() [/usr/bin/node]
 2: 0xa1855c node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0xb9715e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xb974d9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xd54755  [/usr/bin/node]
 6: 0xd54de6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
 7: 0xd616a5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0xd62555 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0xd6500c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0xd2c75e v8::internal::Factory::NewUninitializedFixedArray(int, v8::internal::AllocationType) [/usr/bin/node]
11: 0xe9bc31  [/usr/bin/node]
12: 0xe9bee0  [/usr/bin/node]
13: 0x104484b v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
14: 0x140a8f9  [/usr/bin/node]
```

**Comment by klizhentas** [comment]
@iAdramelk yarn install and yarn dev fails for me now:

```
$ yarn preflight && next dev
warning ../../../../../package.json: No license field
$ yarn build-loaders && yarn add-symlinks
warning ../../../../../package.json: No license field
$ rm -rf __build && ttsc --build tsconfig.loaders.json
warning ../../../../../package.json: No license field
$ node ./scripts/add-symlinks.js
/home/sasha/go/src/github.com/gravitational/next/scripts/add-symlinks.js:9
rmSync(docsPagesRoot, { recursive: true, force: true });
^

TypeError: rmSync is not a function
    at Object.<anonymous> (/home/sasha/go/src/github.com/gravitational/next/scripts/add-symlinks.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by klizhentas** [comment]
Here is a full list from scratch for me:

* Requirements:
 Node > 14.x

```bash
# Install NVM
# https://github.com/nvm-sh/nvm#installing-and-updating
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
# Install node
$ nvm install node --lts
$ npm install --global yarn
$ git clone https://github.com/gravitational/next.git 
$ cd next
$ yarn install
$ git submodule init
$ git submodule update
$ yarn dev
# go to http://localhost:3000/teleport/docs
```

**Comment by iAdramelk** [comment]
Add info about Node and yarn to docs.
