### ISSUE TITLE
Can't run locally: TypeError: rmSync is not a function 

### ISSUE THREAD

**Issue by benarent** [gravitational/next#95]
I was trying to run this locally, looks like the changes to `add-symlinks` has created an issue.

```
➜  next git:(main) ✗ npm run dev

> teleport-docs-next@0.1.0 dev
> yarn preflight && next dev

yarn run v1.22.4
$ yarn build-loaders && yarn add-symlinks
$ rm -rf __build && ttsc --build tsconfig.loaders.json
$ node ./scripts/add-symlinks.js
/Users/benarent/Projects/next/scripts/add-symlinks.js:9
rmSync(docsPagesRoot, { recursive: true, force: true });
^

TypeError: rmSync is not a function
    at Object.<anonymous> (/Users/benarent/Projects/next/scripts/add-symlinks.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code 1
npm ERR! path /Users/benarent/Projects/next
npm ERR! command failed
npm ERR! command sh -c yarn preflight && next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benarent/.npm/_logs/2021-02-10T22_34_12_712Z-debug.log
```

## Details
- Fresh repo clone on Mac

**Comment by klizhentas** [comment]
@benarent update your node version to 1.15. I used nvm to set up the version on my computer. @iAdramelk we need developer install instructions with required versions going forward.

**Comment by iAdramelk** [comment]
@benarent `rmSync` was added in node 14.*, so it will fail if the node version is smaller. You probably have a elder version.

@klizhentas I will try to create docker image today to prevent version errors in the future.

**Comment by klizhentas** [comment]
@iAdramelk no need for docker image for now, but please update the docs with this:

https://github.com/gravitational/teleport/pull/5551
